### ISSUE TITLE
Return DialedHost with DisableCoalesce=true

### ISSUE THREAD

**Issue by martin-sucha** [mpenick/gocqlastra#1]
gocql disables coalescing for TLS connections because TLS connections don't support writev (more info in
https://github.com/gocql/gocql/commit/93aced8f230cbe935a771cf0918959b82b25003e )

Consider returning DisableCoalesce=true from the HostDialer to match gocql's behavior.

**Comment by mpenick** [comment]
Thanks for the pointer!
